#!/bin/bash

# Check if day argument is provided
if [ -z "$1" ]; then
    echo "Usage: ./runday <day> <part>"
    echo "Example: ./runday 1 2"
    exit 1
fi

# Check if part argument is provided
if [ -z "$2" ]; then
    echo "Usage: ./runday <day> <part>"
    echo "Example: ./runday 1 2"
    exit 1
fi

# Validate if the day is a number
if ! echo "$1" | grep -qE '^[0-9]+$'; then
    echo "Invalid day: Please enter a valid number."
    exit 1
fi

# Validate if the part is a number (1 or 2)
if ! echo "$2" | grep -qE '^[12]$'; then
    echo "Invalid part: Please enter 1 or 2."
    exit 1
fi

if [ "$1" -lt 10 ]; then
    DAY=$(printf "%02d" "$1")
else
    DAY=$1
fi

PART=$2

exec go run "Day${DAY}/Part${PART}/main.go"